version: 2

sources:
  - name: jaffle_shop
    schema: public
    tables:
      - name: customers
      - name: orders
      - name: payments

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_email
        tests:
          - not_null
