version: 2

sources:
  - name: jaffle_shop
    schema: public
    tables:
      - name: customers
      - name: orders
      - name: payments

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_email
        tests:
          - not_null

  - name: fact_orders_metrics
    columns:
      - name: order_date
        tests:
          - not_null
      - name: gross_revenue
        tests:
          - not_null
          - positive_value
      - name: repeat_purchase_rate
        tests:
          - is_between_0_and_1
